### ISSUE TITLE
defpool with guards

### ISSUE THREAD

**Issue by randysecrist** [drewkerrigan/riak-elixir-client#59]
@edgurgel:  I don't think the guard for is_pid(pid) is working for guards that are using defpool.

defpool is a macro which happens at compile time.  That means beam can't (may not be able to) prevent function calls with pid variable actually being an atom :error_no_members.  I suppose the question is, does the guard on Riak.find work even when using the defpool macro?

Any thoughts on how to better handle this when application code calls .find?

See this trace for reference:

```
GenServer #PID<0.842.10> terminating
** (FunctionClauseError) no function clause matching in :riak_dt_pb.e_type_bytes/2
    src/riak_dt_pb.erl:905: :riak_dt_pb.e_type_bytes(:error_no_members, <<10, 18, 112, 114, 111, 100, 31, 114, 101, 100, 117, 99, 101, 114, 95, 115, 116, 97, 116, 101, 18, 56, 115, 116, 111, 114, 101, 31, 97, 99, 56, 51, 54, 102, 50, 55, 45, 50, 55, 102, 51, 45, 52, 100, 49, 49, 45, 56, 101, 97, ...>>)
    src/riak_dt_pb.erl:219: :riak_dt_pb.e_msg_dtfetchreq/3
    src/riak_pb_codec.erl:94: :riak_pb_codec.encode/1
    (riakc) src/riakc_pb_socket.erl:2331: :riakc_pb_socket.encode_request_message/1
    (riakc) src/riakc_pb_socket.erl:2303: :riakc_pb_socket.send_request/2

    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
Last message (from #PID<0.504.10>): {:req, {:dtfetchreq, <<112, 114, 111, 100, 31, 114, 101, 100, 117, 99, 101, 114, 95, 115, 116, 97, 116, 101>>, <<115, 116, 111, 114, 101, 31, 97, 99, 56, 51, 54, 102, 50, 55, 45, 50, 55, 102, 51, 45, 52, 100, 49, 49, 45, 56, 101, 97, 101, 45, 50, 98, 102, 98, 52, 55, 100, 56, 53, 48, 51, 48, 31, 115, 101, ...>>, :error_no_members, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, true}, 60000}
State: {:state, 'some.loadbalancer.com', 8087, false, false, #Port<0.102632>, false, :gen_tcp, :undefined, {[], []}, 1, [], :infinity, :undefined, :undefined, :undefined, :undefined, [], 100}
Client #PID<0.504.10> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (riak) lib/riak.ex:305: Riak.find/4
    (riak) lib/riak.ex:304: Riak.find/3
    (riak) lib/riak.ex:285: Riak.find/2
```

**Comment by randysecrist** [comment]
This is what I'm thinking:

https://github.com/drewkerrigan/riak-elixir-client/pull/60

**Comment by randysecrist** [comment]
Maybe we implement our own async retry here?  (try three times over some time frame) to increase the probability that a connection frees up?
